defaults:
  - _self_ 
  - anygrasper: anygrasper
  - dataloader: loader

workspace_limits:
  xmin: -0.19
  xmax: 0.12
  ymin: 0.02
  ymax: 0.15
  zmin: 0.0
  zmax: 1.0

camera:
  fx: 927.17
  fy: 927.37
  cx: 651.32
  cy: 349.62
  scale: 1000.0

debug: true
data_dir: "./data/example_data"