defaults:
  - _self_ 
  - anygrasper: anygrasper
  - dataloader: loader

workspace_limits:
  xmin: -1
  xmax: 1
  ymin: -1
  ymax: 1
  zmin: 0.0
  zmax: 1.0

debug: true
data_dir: "./data/example_data"